### PR TITLE
Add Bagon and Absol Gen III Event moves

### PR DESCRIPTION
**Pull request by AsherNoel1**
http://bulbapedia.bulbagarden.net/wiki/Wish_%28move%29#By_event

First contribution :) I will also add in the move for Metang and Metagross

### CODE REVIEW

**Comment by TheImmortal** [comment]
This repository was for XY learnsets. In addition, these events are already part of Pokemon Showdown's event database located here: https://github.com/Zarel/Pokemon-Showdown/blob/master/data/formats-data.js.

**Comment by AsherNoel** [comment]
The moves are not usable on the Showdown client right now. I did not find them in https://github.com/Zarel/Pokemon-Showdown/blob/master/data/learnsets-g6.js 
Is this the correct location? :[ Or should we not at the moves at all

**Comment by TheImmortal** [comment]
https://raw.githubusercontent.com/Zarel/Pokemon-Showdown/master/data/learnsets.js

They are usable. The teambuilder does not show it but you can battle with it.

**Comment by AsherNoel** [comment]
Wow, that is cool - but it is a hidden secret. Shouldn't we let people know by adding it to team builder?

**Pull request closed without merging**
